name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
        # Install shfmt
        curl -L "https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64" -o shfmt
        chmod +x shfmt
        sudo mv shfmt /usr/local/bin/
        
        # Install bats
        sudo npm install -g bats
    
    - name: Run shellcheck
      run: make lint
    
    - name: Check formatting
      run: make fmt-check
    
    - name: Run tests
      run: make test
    
    - name: Test help output
      run: ./bin/gh-cost-center --help
